---
title: "Luiss Guido Carli | PhD in Politics | Mixed Methods"
---

# Course description

Many researchers are trained in the use of one primary method. Using an innovative method may require them to reach out across their own methods of comfort zone, to think outside their normal everyday methods routine. The course on mixed methods will introduce the students into a rather new set of research methods.

A mixed method research (MMR) is a research program in which methods of different types (qualitative and quantitative) are combined to provide a richer set of insights about the phenomenon under exam (including its context) and to reach greater confidence in the conclusions generated by the research. 

# Learning outcomes

The main goal is to enable the students to enrich and deepen their traditional academic tool-box on methods of social research, and familiarize with the basic elements of mixed methods research (MMR) to learn how to handle the methodological choices they are going to face in preparing their PhD dissertation relying on a larger and new set of options, beyond the purely quantitative and/or purely qualitative approaches, being well aware of the advantages and pitfalls implied in conducting research in applied settings, to get used to deal with and manage to solve the methodological issues students face in their daily research practices (writing up a research proposal, designing research methods, evaluating and selecting of different tools for mixed methods data collection and analysis, writing a mixed-method research report), avoiding ritualized take away recipes, and progressing in their scientific endeavor through peer-to-peer, open and informed debate. Students will also be introduced to the logics and workings of Qualitative Comparative Analysis (QCA).

After completing the module students will be able to:

## Knowledge and understanding

1.  Identify an appropriate research topic,

2.  Spell out research aims and objectives,

## Applying knowledge and understanding

3.  Design an indicative literature review synthesizing material and write it in their own words,

4.  develop a research design and select appropriate methods,

5.  set up a complete and coherent research proposal.

    ## Making judgments

6.  Apply in a coherent and rigorous manner the principles of critical thinking for the purpose of correct and complete understanding of the results of research conducted using alternative and/or similar methodological solutions to those adopted in one’s own study.

7.  Compare the utilised paradigms in mixed or combined methods research and apply the relevant theories to the design and finalization of one’s own research.

    ## Communication skills

8.  Present research results to a peer and general audience.

9.  Present in a rigorous and comprehensive manner, to a multi-disciplinary research audience, the results of the research conducted according to mixed or combined methods.

10. Design and write a research paper and/or report that meets the guiding criteria, styles and heuristic directions typical of mixed or combined methods studies.

    ## Learning skills

    The course aims to broaden the range of methodological skills and technical solutions applicable in field research along three lines:

    11. Attention to scientifically relevant innovations emerging in the methodological field (according to both quantitative and qualitative approaches).
    12. Systematic care applied to the research processes, in particular for what concerns the activities in the field and intended for the direct and technically consistent measurement of the phenomena under investigation.
    13. Assessment of the integrability and effective integration of the quantitative and/or qualitative information bases constructed in the course of field research.

# Entry requirements

Successful completion of the first-year courses of the PhD in Politics.

# Reference book

-   Seawright, J. (2016). *Multi-Method Social Science: Combining Qualitative and Quantitative Tools*. Cambridge University Press.

    <!--#Creswell, J. W. (2021). A concise introduction to mixed methods research. SAGE publications.  -->

# Teaching method

Lectures followed by open discussions with students. Students will be engaged in numerous activities during the semester (reading, presentations, discussions, exploration and research, debate and writing).

# Course contents

## **Week 1**

**Introduction to the course and to Mixed Method Research (MMR)**

[**Please come to class prepared to give a brief introduction of yourself and of your research project.**]{.underline}

### [Slides Week 1](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/EWEFYGPUyypFk8jZ3cVsDP8B85TQ6WBQ_Qy0F85Q3PAIrw?e=iOnTmY "Slides Week 1")

### Readings:

-   [Collier, D., & Elman, C. (2008). Qualitative and Multimethod Research. In *The Oxford Handbook of Political Methodology* (pp. 779-795). Oxford University Press.](https://luiss.alma.exlibrisgroup.com/discovery/openurl?institution=39LLUISSGC_INST&vid=39LLUISSGC_INST:Services&%3Fctx_ver=Z39.88-2004&ctx_enc=info:ofi%2Fenc:UTF-8&rfr_id=info:sid%2Fsummon.serialssolutions.com&rft_val_fmt=info:ofi%2Ffmt:kev:mtx:book&rft.genre=bookitem&rft.title=The%20Oxford%20Handbook%20of%20Political%20Methodology&rft.au=Collier,%20David&rft.au=Elman,%20Colin&rft.atitle=Qualitative%20and%20Multimethod%20Research:%20Organizations,%20Publication,%20and%20Reflections%20on%20Integration&rft.series=Oxford%20Handbooks%20of%20Political%20Science&rft.date=2008-08-21&rft.pub=Oxford%20University%20Press&rft.isbn=9780199286546&rft_id=info:doi%2F10.1093%2Foxfordhb%2F9780199286546.003.0034&rft.externalDocID=10_1093_oxfordhb_9780199286546_003_0034¶mdict=en-EN)

-   [Franklin, C. (2008). Quantitative Methodology. In *The Oxford Handbook of Political Methodology* (pp. 796-813). Oxford University Press.](https://luiss.alma.exlibrisgroup.com/discovery/openurl?institution=39LLUISSGC_INST&vid=39LLUISSGC_INST:Services&%3Fctx_ver=Z39.88-2004&ctx_enc=info:ofi%2Fenc:UTF-8&rfr_id=info:sid%2Fsummon.serialssolutions.com&rft_val_fmt=info:ofi%2Ffmt:kev:mtx:book&rft.genre=bookitem&rft.title=The%20Oxford%20Handbook%20of%20Political%20Methodology&rft.au=Franklin,%20Charles%20H&rft.atitle=Quantitative%20Methodology&rft.series=Oxford%20Handbooks%20of%20Political%20Science&rft.date=2008-08-21&rft.pub=Oxford%20University%20Press&rft.isbn=9780199286546&rft_id=info:doi%2F10.1093%2Foxfordhb%2F9780199286546.003.0035&rft.externalDocID=10_1093_oxfordhb_9780199286546_003_0035¶mdict=en-EN)

-   [Bernhard, M. (2009). Methodological disputes in comparative politics. Comparative Politics, 41(4), 495-515.](https://luiss.alma.exlibrisgroup.com/discovery/openurl?institution=39LLUISSGC_INST&vid=39LLUISSGC_INST:Services&%3Fctx_ver=Z39.88-2004&ctx_enc=info:ofi%2Fenc:UTF-8&rfr_id=info:sid%2Fsummon.serialssolutions.com&rft_val_fmt=info:ofi%2Ffmt:kev:mtx:journal&rft.genre=article&rft.atitle=Methodological%20Disputes%20in%20Comparative%20Politics&rft.jtitle=Comparative%20politics&rft.au=Bernhard,%20Michael&rft.date=2009-07-01&rft.pub=City%20University%20of%20New%20York&rft.issn=0010-4159&rft.volume=41&rft.issue=4&rft.spage=495&rft.epage=515&rft_id=info:doi%2F10.5129%2F001041509X12911362972638&rft.externalDocID=40599220¶mdict=en-EN)<https://doi.org/10.5129/001041509X12911362972638>

### Examples:

-   Cremaschi, S., Bariletto, N., & De Vries, C. E. (2025). Without Roots: The Political Consequences of Collective Economic Shocks. *American Political Science Review*, 1–20.\
    [https://doi.org10.1017/S0003055425000073](https://doi.org/10.1017/S0003055425000073)

<!-- -->

-   Larson, J. M., & Lewis, J. I. (2018). Rumors, Kinship Networks, and Rebel Group Formation. *International Organization*, 72(4), 871-903. <https://doi.org/10.1017/S0020818318000243>   

-   Lupu, N. (2014). Brand Dilution and the Breakdown of Political Parties in Latin America. *World Politics*, 66(4), 561-602. <https://doi.org/10.1017/S0043887114000197>

## **Week 2**

**The Logics of Quantitative and Qualitative Research**

### [Slides Week 2](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/EQXdbRjbv2xLrx9HkYXNzW0BASOb9BErjjApmMKaYN7rBQ?e=0D0Rvp "Slides Week 2")

### Readings

-   [Seawright, J. (2016). *Multi-Method Social Science: Combining Qualitative and Quantitative Tools* (Chapter 2). Cambridge University Press.](https://go.exlibris.link/m47rfDcZ)

-   Mahoney, J. (2008). Toward a Unified Theory of Causality. *Comparative Political Studies, 41*(4-5), 412-436. <https://doi.org/10.1177/0010414007313115>

-   Mahoney, J., & Goertz, G. (2006). A Tale of Two Cultures: Contrasting Quantitative and Qualitative Research. *Political Analysis, 14*(3), 227-249. <https://doi.org/10.1093/pan/mpj017>

-   [Bartels, L. M. (2010). Some Unfulfilled Promises of Quantitative Imperialism. In H. E. Brady & D. Collier (Eds.), *Rethinking Social Inquiry: Diverse Tools, Shared Standards* (pp. 85-92). Rowman & Littlefield.](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/EQzlgj5uBfRDiKQW6HqbEEIBJUV5ZYGFOhiO7l3z5JLogQ?e=tbjSSQ)

## **Week 3**

**Somewhere in between? Qualitative Comparative Analysis (QCA)**

### [Slides Week](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/EdsvSPKd8m9Onc8h9rkdGAEBfP3dHO20OkLDd2qUXU24oQ?e=tElokf "Slides Week 3")[3](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/EdsvSPKd8m9Onc8h9rkdGAEBfP3dHO20OkLDd2qUXU24oQ?e=tElokf "Slides Week 3-4")

### Readings:

-   Wagemann, C. (2017). Qualitative Comparative Analysis (QCA) and Set Theory. *Oxford Research Encyclopedia of Politics.* <https://doi.org/10.1093/acrefore/9780190228637.013.247>

-   [Oana, I. E., Schneider, C. Q., & Thomann, E. (2021). *Qualitative Comparative Analysis Using R: A Beginner's Guide.* Cambridge University Press. Chapters: 1-4.](https://go.exlibris.link/jHgBy7Bv)

-   Mahoney, J., & Vanderpoel, R. S. (2015). Set Diagrams and Qualitative Research. *Comparative Political Studies, 48*(1), 65-100. <https://doi.org/10.1177/0010414013519410>

-   Ragin, C. C. (2013). New Directions in the Logic of Social Inquiry. *Political Research Quarterly, 66*(1), 171-174. <https://doi.org/10.1177/1065912912468269>

-   Mahoney, J. (2010). After KKV: The New Methodology of Qualitative Research. *World Politics, 62*(1), 120-147. <https://doi.org/10.1017/S0043887109990220>

### Examples:

-   Cebotari, V., & Vink, M. P. (2013). A configurational analysis of ethnic protest in Europe. *International Journal of Comparative Sociology, 54*(4), 298-324.\
    <https://doi.org/10.1177/0020715213508567>

-   A searchable database of journal articles using QCA from various fields of research can be found at [COMPASSS](http://www.compasss.org/bibdata.htm).

## **Week 4**

**Somewhere in between? Qualitative Comparative Analysis (QCA)**

### [Material Week 4](https://luiss-my.sharepoint.com/:u:/g/personal/fvisconti_luiss_it/EXGmwFPFR-JFiPry-j11UZEBLBPT-5hhuEAc6mNPOJKu0A?e=ok9X9E "Material Week 4")

## **Week 5**

**The logic and design of MMR**

### [Slides week 5](https://luiss-my.sharepoint.com/:u:/g/personal/fvisconti_luiss_it/EbJDratMOoVCseA_FlpL3CABgpDif5dqMX2Yp5hqiGtFdg?e=E8glS0 "Mattia week 5")

### Readings:

-   [Seawright, J. (2016). *Multi-Method Social Science: Combining Qualitative and Quantitative Tools* (Chapter 1). Cambridge University Press.](https://go.exlibris.link/m47rfDcZ)

-   [Creswell, J. W., & Plano Clark, V. L. (2011). *Designing and Conducting Mixed Methods Research* (2nd ed., Chapters 1, 2, 3). Sage Publications.](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/ERF-QAwZpshBlKn6s5sfjQcBGq1dytup-z4vAxrx008ioQ?e=F6WsET)

-   Maggetti, M. (2020). Mixed-methods designs. Handbuch Methoden der Politikwissenschaft, 193-210. [Available here](https://maggetti.org/wp-content/uploads/2020/06/Maggetti-Mixed-methods-designs.pdf).

-   Schoonenboom, J., & Johnson, R. B. (2017). How to construct a mixed methods research design. *Kölner Zeitschrift für Soziologie und Sozialpsychologie*, *69*(2), 107-131. <https://doi.org/10.1007/s11577-017-0454-1>

## **Week 6**

**Case Studies and MMR**

### [Material week 6](https://luiss-my.sharepoint.com/:u:/g/personal/fvisconti_luiss_it/EYJS0qZcfrFLrkEHGHnKYJQBsO-Ha6FT9rtti5aVx25Kog?e=BkjHnZ)

### Required readings:

-   [Gerring, J. (2006). What is a Case Study and What is a Case Study Good For? In *Case Study Research: Principles and Practices* (pp. 17-64). Cambridge University Press.](https://go.exlibris.link/v5QhSXCP)

-   [Seawright, J. (2016). *Multi-Method Social Science: Combining Qualitative and Quantitative Tools* (Chapter 8). Cambridge University Press.](https://go.exlibris.link/m47rfDcZ)

-   Collier, D. (2011). Understanding Process Tracing. *PS: Political Science & Politics, 44*(4), 823-830. <https://doi.org/10.1017/S1049096511001429>

### Examples:

-   Mattingly, D. (2016). Elite Capture: How Decentralization and Informal Institutions Weaken Property Rights in Rural China. *World Politics, 68*(3), 383-412. <https://doi.org/10.1017/s0043887116000083>

-   Clarke, K., & Kocak, K. (2020). Launching Revolution: Social Media and the Egyptian Uprising’s First Movers. *British Journal of Political Science, 50*(3), 1025-1045. <https://doi.org/10.1017/S0007123418000194>

## **Week 7**

**Regression Analysis in MMR**

### [Slides week 7](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/Eb68Yqgq8vpGoHFRwDnqkmIBChvtajS-6Ilv5zdQesG1KA?e=dCCWFx)

### Readings:

-   [Seawright, J. (2016). *Multi-Method Social Science: Combining Qualitative and Quantitative Tools* (Chapter 3). Cambridge University Press.](https://go.exlibris.link/m47rfDcZ)

-   Coppedge, M. (1999). Thickening Thin Concepts and Theories: Combining Large-N and Small-N in Comparative Politics. *Comparative Politics, 31*(4), 465-476. <https://doi.org/10.2307/422240>

-   Lieberman, E. (2005). Nested Analysis as a Mixed-Method Strategy for Comparative Research. *American Political Science Review, 99*(3), 435-452. <https://doi.org/10.1017/S0003055405051762>

-   Achen, C. H. (2005). Let's Put Garbage-Can Regressions and Garbage-Can Probits Where They Belong. *Conflict Management and Peace Science, 22*(4), 327-339. <https://doi.org/10.1080/07388940500339167>

### Examples:

-   De Bruin, E. (2018). Preventing Coups D’état: How Counterbalancing Works. *Journal of Conflict Resolution, 62*(7), 1433-1458. <https://doi.org/10.1177/0022002717692652>

-   Wasow, O. (2020). Agenda Seeding: How 1960s Black Protests Moved Elites, Public Opinion, and Voting. *American Political Science Review, 114*(3), 638-659. <https://doi.org/10.1017/S000305542000009X>

-   Cassani, A., Luppi, F., & Natalizia, G. (2016). Pathways of democratisation to human development in post‐communist countries. *European Journal of Political Research*, 55(3), 512-530.\
    <https://doi.org/10.1111/1475-6765.12140>

## **Week 8**

**Fieldwork, Interviews, Ethnography in MMR**

### [Slides week 8](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/EaQ8q-CQNvpNrV62AMqgxhcBH5QrpA25_snEnh1iM0nRvg?e=98hBff)

### Readings:

-   [Wood, E. J. (2007). Field Research. In C. Boix & S. Stokes (Eds.), *The Oxford Handbook of Comparative Politics* (pp. 123-146). Oxford University Press.](https://go.exlibris.link/dcrkHX5L)

-   [Kapiszewski, D., & MacLean, L. M. (2015). Interviews, Focus Groups, and Oral Histories. In *Field Research in Political Science* (pp. 190-233). Cambridge University Press.](https://go.exlibris.link/Pqhk30p3)

-   [Fujii, L. A. (2018). *Interviewing in Social Science Research: A Relational Approach* (Chapter 1). Routledge.](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/EVwgG28I59xOm8RWOOnuSRoBjxSdCDcR-JgnJ8UT6JTe4w?e=36sR9P)

-   Boswell, J., Corbett, J., Dommett, K., Jennings, W., Flinders, M., Rhodes, R. A. W., & Wood, M. (2019). State of the Field: What Can Political Ethnography Tell Us About Anti-Politics and Democratic Disaffection? *European Journal of Political Research, 58*(1), 56-71. <https://doi.org/10.1111/1475-6765.12270>

-   [Creswell, J. W., Hanson, W. E., & Morales, A. (2006). How Interpretive Qualitative Research Extends Mixed Methods Research. *Research in the Schools, 13*(1), 1-11.](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=97d962208ddefbf01b3de936446c0ee20381df10)

### Examples:

-   Gowayed, H. (2018). The Unnecessary Nudge: Education and Poverty Policy in a Cairo Slum. *Sociological Forum, 33*(2), 299-318. <https://doi.org/10.1111/socf.12421>

-   Thachil, T. (2018). Improving Surveys Through Ethnography: Insights from India’s Urban Periphery. *Studies in Comparative International Development, 53*(3), 281-299. <https://doi.org/10.1007/s12116-018-9272-3>

## **Week 9**

**Experimental evidence in MMR**

### Readings:

-   [Seawright, J. (2016). *Multi-Method Social Science: Combining Qualitative and Quantitative Tools* (Chapter 7). Cambridge University Press.](https://go.exlibris.link/m47rfDcZ)

-   [Dunning, T. (2012). *Natural Experiments in the Social Sciences: A Design-Based Approach* (Chapters 1 and 11). Cambridge University Press.](https://luiss-my.sharepoint.com/:b:/g/personal/fvisconti_luiss_it/ERbWgVO8wpJCp_WZzsDyorUBg98yRFO8YpZ3N_hl4TvvTA?e=VBq8Ig)

-   Paluck, E. L. (2010). The Promising Integration of Field Experimentation and Qualitative Methods. *Annals of the American Academy of Political and Social Science, 628*, 59-71. <https://doi.org/10.1177/0002716209351510>

-   Dunning, T. (2016). Transparency, Replication, and Cumulative Learning: What Experiments Alone Cannot Achieve. *Annual Review of Political Science, 19*, 545-563. <https://doi.org/10.1146/annurev-polisci-042114-015939>

### Examples:

-   Arjona, A. (2016). Institutions, Civilian Resistance, and Wartime Social Order: A Process-Driven Natural Experiment in the Colombian Civil War. *Latin American Politics and Society, 58*(3), 99-122. <https://doi.org/10.1111/j.1548-2456.2016.00320.x>

-   Nugent, E. R. (2020). The Psychology of Repression and Polarization. *World Politics, 72*(2), 291-334. <https://www.cambridge.org/core/journals/world-politics/article/psychology-of-repression-and-polarization/F057EBF90523A818EFF59B6B2FC44D60>

-   Raffler, P. J. (2022). Does Political Oversight of the Bureaucracy Increase Accountability? Field Experimental Evidence from a Dominant Party Regime. *American Political Science Review, 116*(4), 1443-1459. <https://doi.org/10.1017/S0003055422000181>

## **Week 10**

**Transparency and replicability of MMR**

### Readings

-   Blair, G., Cooper, J., Coppock, A., & Humphreys, M. (2019). Declaring and Diagnosing Research Designs. *American Political Science Review, 113*(3), 838-859. <https://doi.org/10.1017/S0003055419000194>

-   Data Access and Research Transparency (DA-RT): A Joint Statement by Political Science Journal Editors. (2015). *Political Science Research and Methods, 3*(3), 421. <https://doi.org/10.1017/psrm.2015.44>

-   Jacobs, A. M., Büthe, T., Arjona, A., Arriola, L. R., Bellin, E., Bennett, A., … Yashar, D. J. (2021). The Qualitative Transparency Deliberations: Insights and Implications. *Perspectives on Politics*, *19*(1), 171–208. <https://doi.org/10.1017/S1537592720001164>

# Assessment

The final course grade will be expressed in thirtieths (/30). A pass mark will be attained with a minimum mark of 18/30, while the maximum mark will be 30/30 cum laude. The course will require both active class participation and a successful completion of a number of tasks/activities as follows:

## *Participation in class*

Students will be expected to attend all the seminars and contribute to class discussions. It is essential that course participants prepare fully for classes by reading the required material. Participation will contribute to 15% of the final grade.

## *Class presentation*

Each student will have to present to the class at least one scientific article listed among the examples of the second part of the course (week 6 to 9) and discuss the research design along with its strengths and weaknesses. The presentation will contribute to 25% of the final grade.

## *Final paper*

This is the main requirement for the course (60% of the final grade). The paper will serve as an important exercise in how to design a social science research proposal that includes a mixed method design and will hopefully serve as the basis for students’ dissertation project. The paper should contain (1) the central research question(s), (2) the literature and/or debate it seeks to address, (3) the argument or theory/hypotheses, (4) a description of the mixed method design to be used in the project, (5) case selection criteria, and (6) a plan for data collection and analysis that will serve to answer the research question(s). The paper should be between 3,000 and 4,000 words.

# Academic Honesty

Any student who commits an act of academic dishonesty will receive a failing grade on the work in which the dishonesty occurred. In addition, acts of academic dishonesty, irrespective of the weight of the assignment, may result in the student receiving a failing grade in the course. Instances of academic dishonesty will be reported to the Director of the PhD program.
